// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrAhnV-fb8yxhGSATfDYCESehaKwDlNfk',
    appId: '1:690058154429:web:9fb35f03d5ab345500c2d4',
    messagingSenderId: '690058154429',
    projectId: 'contact-save-2f91b',
    authDomain: 'contact-save-2f91b.firebaseapp.com',
    storageBucket: 'contact-save-2f91b.appspot.com',
    measurementId: 'G-B08K70X3VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV3O6QxUkMGi9RGQBgcC7EZ-EJ8zhT270',
    appId: '1:690058154429:android:edb82a7f83bf300800c2d4',
    messagingSenderId: '690058154429',
    projectId: 'contact-save-2f91b',
    storageBucket: 'contact-save-2f91b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF_jFnZ-9iySk69I7hHhORWFl6zMyNWtw',
    appId: '1:690058154429:ios:8c441272d2e4f34200c2d4',
    messagingSenderId: '690058154429',
    projectId: 'contact-save-2f91b',
    storageBucket: 'contact-save-2f91b.appspot.com',
    iosBundleId: 'com.example.platformConverterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF_jFnZ-9iySk69I7hHhORWFl6zMyNWtw',
    appId: '1:690058154429:ios:8c441272d2e4f34200c2d4',
    messagingSenderId: '690058154429',
    projectId: 'contact-save-2f91b',
    storageBucket: 'contact-save-2f91b.appspot.com',
    iosBundleId: 'com.example.platformConverterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrAhnV-fb8yxhGSATfDYCESehaKwDlNfk',
    appId: '1:690058154429:web:6fd68b8f8a7b773500c2d4',
    messagingSenderId: '690058154429',
    projectId: 'contact-save-2f91b',
    authDomain: 'contact-save-2f91b.firebaseapp.com',
    storageBucket: 'contact-save-2f91b.appspot.com',
    measurementId: 'G-5ZV4RQHFFH',
  );

}